// app/layout.tsx

/* RootLayout は「殻」に徹する */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { notoSansJp } from '@/app/theme/fonts'
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Apline",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={notoSansJp.variable} suppressHydrationWarning>
      {/**ServerとClientでThemeが違う部分を吸収 */}
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
